import Sidenav from '@/app/Sidenav';
import Photosite from "@/app/photosite";
import Social from "@/app/Social";
import "./globals.css";
import styles from "./page.module.css";

export const metadata = {
  title: "Продажа веб сайтов",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/icons/favicon.png" sizes="any" type="image/x-icon" />
      </head>
      <body>
      <div className={styles.page}>
        <Sidenav/>
        <Photosite/>
        {children}
        <Social/>
        </div>
      </body>
    </html>
  );
}
